# Generated by Django 5.2 on 2025-04-08 10:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название')),
                ('seats', models.IntegerField(help_text='Укажите количество посадочных мест', verbose_name='Количество столиков')),
                ('location', models.CharField(help_text='Например: У окна, Терраса, VIP-зона и т.д.', max_length=128, verbose_name='Локация')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(help_text='ФИО или имя для бронирования', max_length=128, verbose_name='Имя клиента')),
                ('reservation_time', models.DateTimeField(db_index=True, verbose_name='Время бронирования')),
                ('duration_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(30, message='Минимальная бронь 30 минут')], verbose_name='Длительность брони')),
                ('table', models.ForeignKey(help_text='Выберите столик для бронирования', on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='application.table', verbose_name='Столик')),
            ],
            options={
                'ordering': ['reservation_time'],
            },
        ),
    ]
